Add Dirge
Chris-plus-alphanumericgibberish/dNAO pull request #1080
Opened 2020-08-09 04:11 UTC by RikerW

~~Stolen~~ Inspired by EvilHack Dirge.

* chaotic intelligent knight-favoring malleable long sword
** Will always evade the grasp of non-chaotics and non-knights, you must be a chaotic knight to wield. Helms of opposite alignment are accepted for wielding purposes.
* Can only be obtained by same-race sacrifice on a chaotic altar, while a permanently chaotic knight wielding a long sword. This will convert the long sword into Dirge, rustproofing it, clearing erosion, and setting enchantment to 0 if it was previously lower. This will not uncurse it.
* Has +5 to hit and +1d10 acid damage
* Has +6 unholy damage when cursed
* Permanently coated in acid poison
* Grants acid resistance when wielded

This is mostly just a feature suggestion I wanted to get out there. It seems like fun, if not particularly balanced, and shouldn't be too busted since it requires a permanent conversion to chaotic to get. Should be only marginally stronger than Excalibur in general, and much less useful in the late game considering the extra d10 acid vs 3d7 holy. Thoughts?

2020-08-09 05:38 UTC, Chris-plus-alphanumericgibberish commented
Could give it the self-acidifying property instead of a permanent coat of acid poison.  Self-acidifying means that the first few hits of every fight have the extra acid damage, then it drops back to +1d10 only.

2020-08-09 14:35 UTC, RikerW commented
The intention was only acid poison, but I'm considering making it poisoned instead (mainly since that much acid damage is kinda weird). Poison is definitely a nerf for endgame damage, but does have the instakill vs some foes. I also considered filth, but that's stupid as a permanent due to the instakill chance. 

Yeah, the average damage is supposed to be equal to or possibly a tad lower than excalibur. It may need to go lower still, considering this can be drooled on, but I'm not sure yet.

2020-08-10 23:32 UTC, NeroOneTrueKing requested changes
As written, Dirge has no bonus unholy damage, which doesn't match your design notes. Please confirm.

Edit: it looks cool and I like it

2020-09-05 23:23 UTC, Chris-plus-alphanumericgibberish approved these changes

2020-09-05 23:24 UTC, merged