Double maxweight per size above medium
Chris-plus-alphanumericgibberish/dNAO pull request #1365
Opened 2020-12-31 19:38 UTC by RikerW

Since weapon weights are doubled, it makes sense you should be able to use appropriately sized items.

2020-12-31 19:49 UTC, NeroOneTrueKing commented
I see this doesn't penalize gnomes 😄

2020-12-31 19:52 UTC, NeroOneTrueKing requested changes
There are two places in weapon.c that calculate maxweight of offhand weapons -- one for damage, and one for accuracy. The offhand-weight calculation could be moved into its own function, or you can just do the modification in both places.

Gnomes notwithstanding (it's fine by me if they don't get additional penalties, I suppose).

2021-01-05 20:22 UTC, RojjaCebolla commented
just FYI gnomes are still bad

2021-01-06 15:42 UTC, NeroOneTrueKing requested changes
Just noticed another issue, actually.
This commit changes offhand limits like so:
Medium = 1x
Large = 2x
Huge = 4x
Gigantic = 10x

But the weight of those items is 
Medium = 1x
Large = 2x
Huge = 3x
Gigantic = 6x

The formula:
`maxweight *= 2*(youracedata->msize - MZ_MEDIUM);`
should instead be
`maxweight *= 1+(youracedata->msize - MZ_MEDIUM);`

I'm going to ignore the unrelated commits that snuck in; hopefully they won't cause any merge conflicts.

2021-01-07 18:59 UTC, closed without merging