Modfiy DEADMONSTER() macro to claim player is alive, not dead.
Chris-plus-alphanumericgibberish/dNAO pull request #1565
Opened 2021-06-19 21:34 UTC by NeroOneTrueKing

We can avoid checking the player's hp, as when the player is truly dead, things tend to be quickly resolved anyways.

2021-06-22 18:20 UTC, Chris-plus-alphanumericgibberish requested changes, later dismissed

2021-06-22 18:20 UTC, Chris-plus-alphanumericgibberish commented on src/xhity.c
> -							struct monst *mdef2 = u.uswallow ? u.ustuck :
There's a regression here. This specific instance won't lead to the player attacking themselves, but it's unlikely they ever want to attack their own square.

2021-06-22 18:20 UTC, Chris-plus-alphanumericgibberish commented on src/xhity.c
> -							struct monst *mdef2 = !youagr ? m_u_at(tarx + dx, tary + dy) :
This regresses the engulfer-self-attack bug :(

2021-06-23 00:05 UTC, NeroOneTrueKing commented
Not sure how that regression snuck in, so I remade the branch and force-pushed. All better now!

2021-06-24 04:38 UTC, Chris-plus-alphanumericgibberish approved these changes

2021-06-24 04:38 UTC, merged